"use client";

import { ImagePlus, Save, WandSparkles } from "lucide-react";
import { useState, useTransition } from "react";
import { createAuctionAction, updateAuctionAction, uploadAuctionCoverImageAction } from "@/hooks/actions/auctionActions";
import { fromDateTimeLocalBrt, toDateTimeLocalBrt } from "@/lib/auctions/admin-utils";
import { slugifyAuction } from "@/lib/auctions/form-mappers";
import type { AuctionAdmin, AuctionInput } from "@/types/auction-admin";
import type { AuctionCapabilities } from "@/components/Management/capabilities";

type FormState = { title: string; slug: string; category: "ANIMAL" | "MACHINE"; mode: "TIMED" | "LIVE" | "SHOPPING"; description: string; regulationText: string; paymentText: string; deliveryText: string; startsAt: string; endsAt: string; preBidStartsAt: string; preBidEndsAt: string; incrementReais: string; secondaryIncrementReais: string; extensionMinutes: string; plannedLotCount: string };
const emptyState: FormState = { title:"", slug:"", category:"ANIMAL", mode:"LIVE", description:"", regulationText:"", paymentText:"", deliveryText:"", startsAt:"", endsAt:"", preBidStartsAt:"", preBidEndsAt:"", incrementReais:"", secondaryIncrementReais:"", extensionMinutes:"", plannedLotCount:"" };
function cents(value?: number | null) { return value == null ? "" : String(value / 100).replace(".", ","); }
function parseCents(value: string) { const normalized = value.trim().replace(/\./g, "").replace(",", "."); if (!normalized || !/^\d+(\.\d{1,2})?$/.test(normalized)) return undefined; return Math.round(Number(normalized) * 100); }

export function AuctionForm({ initialData, capabilities }: { initialData?: AuctionAdmin; capabilities: AuctionCapabilities }) {
  const [form, setForm] = useState<FormState>(() => initialData ? { title:initialData.title, slug:initialData.slug, category:initialData.category ?? "ANIMAL", mode:initialData.mode, description:initialData.description ?? "", regulationText:initialData.regulationText ?? "", paymentText:initialData.paymentText ?? "", deliveryText:initialData.deliveryText ?? "", startsAt:toDateTimeLocalBrt(initialData.startsAt), endsAt:toDateTimeLocalBrt(initialData.endsAt), preBidStartsAt:toDateTimeLocalBrt(initialData.preBidStartsAt), preBidEndsAt:toDateTimeLocalBrt(initialData.preBidEndsAt), incrementReais:cents(initialData.incrementCents), secondaryIncrementReais:cents(initialData.secondaryIncrementCents), extensionMinutes:initialData.extensionMinutes == null ? "" : String(initialData.extensionMinutes), plannedLotCount:String(initialData.plannedLotCount || "") } : emptyState);
  const [cover, setCover] = useState<File | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const readOnly = initialData ? !capabilities.canEdit : !capabilities.canCreate;
  function update<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (readOnly) return;
    startTransition(async () => {
      const input: AuctionInput = { title:form.title.trim(), slug:form.slug.trim() || slugifyAuction(form.title), category:form.category, mode:form.mode, description:form.description.trim() || undefined, regulationText:form.regulationText.trim() || undefined, paymentText:form.paymentText.trim() || undefined, deliveryText:form.deliveryText.trim() || undefined, startsAt:fromDateTimeLocalBrt(form.startsAt) ?? "", endsAt:fromDateTimeLocalBrt(form.endsAt), preBidStartsAt:fromDateTimeLocalBrt(form.preBidStartsAt), preBidEndsAt:fromDateTimeLocalBrt(form.preBidEndsAt), incrementCents:parseCents(form.incrementReais), secondaryIncrementCents:form.secondaryIncrementReais ? parseCents(form.secondaryIncrementReais) ?? null : null, extensionMinutes:form.extensionMinutes ? Number(form.extensionMinutes) : undefined, plannedLotCount:form.plannedLotCount ? Number(form.plannedLotCount) : undefined };
      const result = initialData ? await updateAuctionAction(initialData.id, input) : await createAuctionAction(input);
      if (!result.success || !result.data) { setNotice(result.error || "Não foi possível salvar os dados."); return; }
      if (cover) { const imageResult = await uploadAuctionCoverImageAction(result.data.id, cover); if (!imageResult.success) { setNotice(`Dados salvos, mas a capa não foi enviada: ${imageResult.error || "erro desconhecido"}`); return; } }
      setNotice(initialData ? "Dados do leilão atualizados." : "Leilão criado. Agora adicione os lotes.");
      if (!initialData) window.location.assign(`/admin/leiloes/${result.data.id}?aba=lotes`); else window.location.reload();
    });
  }
  return <section className="rounded-2xl border border-[#dfe8e2] bg-white p-4 shadow-sm sm:p-6" aria-labelledby="auction-data-title"><div className="flex flex-col gap-2 border-b border-[#e9efeb] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="auction-data-title" className="text-xl font-bold">Dados do leilão</h2><p className="mt-1 text-sm text-slate-600">Esses dados são enviados ao backend e usados pelo catálogo e pelo motor oficial.</p></div>{readOnly ? <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">Somente leitura</span> : null}</div>
    <form onSubmit={submit} className="mt-5 space-y-6"><div className="grid gap-5 lg:grid-cols-2"><Field label="Título" id="auction-title"><input id="auction-title" value={form.title} onChange={(e) => update("title", e.target.value)} required disabled={readOnly} className="admin-field" /></Field><Field label="Slug" id="auction-slug"><div className="flex gap-2"><input id="auction-slug" value={form.slug} onChange={(e) => update("slug", e.target.value)} required disabled={readOnly} className="admin-field min-w-0 flex-1" /><button type="button" onClick={() => update("slug", slugifyAuction(form.title))} disabled={readOnly} className="inline-flex min-h-10 shrink-0 items-center gap-1 rounded-lg border border-[#dfe8e2] px-3 text-xs font-semibold text-[#075b3e] hover:bg-[#e8f4ee] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24] disabled:opacity-50"><WandSparkles className="size-3.5" aria-hidden="true" />Gerar</button></div></Field><Field label="Categoria" id="auction-category"><select id="auction-category" value={form.category} onChange={(e) => update("category", e.target.value as FormState["category"])} disabled={readOnly} className="admin-field"><option value="ANIMAL">Animais</option><option value="MACHINE">Máquinas</option></select></Field><Field label="Formato" id="auction-mode"><select id="auction-mode" value={form.mode} onChange={(e) => update("mode", e.target.value as FormState["mode"])} disabled={readOnly} className="admin-field"><option value="LIVE">Ao vivo</option><option value="TIMED">Pré-lance</option><option value="SHOPPING">Shopping</option></select></Field></div>
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Início" id="auction-starts"><input id="auction-starts" type="datetime-local" value={form.startsAt} onChange={(e) => update("startsAt", e.target.value)} required disabled={readOnly} className="admin-field" /></Field><Field label="Encerramento" id="auction-ends"><input id="auction-ends" type="datetime-local" value={form.endsAt} onChange={(e) => update("endsAt", e.target.value)} disabled={readOnly} className="admin-field" /></Field><Field label="Pré-lance começa" id="auction-pre-start"><input id="auction-pre-start" type="datetime-local" value={form.preBidStartsAt} onChange={(e) => update("preBidStartsAt", e.target.value)} disabled={readOnly} className="admin-field" /></Field><Field label="Pré-lance termina" id="auction-pre-end"><input id="auction-pre-end" type="datetime-local" value={form.preBidEndsAt} onChange={(e) => update("preBidEndsAt", e.target.value)} disabled={readOnly} className="admin-field" /></Field></div>
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Incremento (R$)" id="auction-increment"><input id="auction-increment" value={form.incrementReais} onChange={(e) => update("incrementReais", e.target.value)} inputMode="decimal" placeholder="100,00" disabled={readOnly} className="admin-field" /></Field><Field label="Incremento secundário (R$)" id="auction-secondary"><input id="auction-secondary" value={form.secondaryIncrementReais} onChange={(e) => update("secondaryIncrementReais", e.target.value)} inputMode="decimal" placeholder="Opcional" disabled={readOnly} className="admin-field" /></Field><Field label="Extensão (minutos)" id="auction-extension"><input id="auction-extension" value={form.extensionMinutes} onChange={(e) => update("extensionMinutes", e.target.value)} type="number" min="0" max="120" disabled={readOnly} className="admin-field" /></Field><Field label="Lotes planejados" id="auction-planned-lots"><input id="auction-planned-lots" value={form.plannedLotCount} onChange={(e) => update("plannedLotCount", e.target.value)} type="number" min="0" disabled={readOnly} className="admin-field" /></Field></div>
      <Field label="Descrição" id="auction-description"><textarea id="auction-description" value={form.description} onChange={(e) => update("description", e.target.value)} rows={4} disabled={readOnly} className="admin-field h-auto py-2" /></Field><div className="grid gap-5 lg:grid-cols-3"><TextAreaField label="Regulamento" id="auction-regulation" value={form.regulationText} onChange={(v) => update("regulationText", v)} disabled={readOnly} /><TextAreaField label="Pagamento" id="auction-payment" value={form.paymentText} onChange={(v) => update("paymentText", v)} disabled={readOnly} /><TextAreaField label="Entrega" id="auction-delivery" value={form.deliveryText} onChange={(v) => update("deliveryText", v)} disabled={readOnly} /></div>
      <Field label="Capa do leilão" id="auction-cover"><div className="flex flex-col gap-3 rounded-xl border border-dashed border-[#b7cfc2] bg-[#fbfdfb] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-800">{cover?.name || (initialData?.coverImageUrl || initialData?.coverImage ? "Capa já cadastrada" : "Nenhuma capa selecionada")}</p><p className="mt-1 text-xs text-slate-500">PNG, JPG ou WEBP. O arquivo é enviado ao backend após salvar.</p></div><label className="inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-lg border border-[#dfe8e2] px-3 text-xs font-semibold text-[#075b3e] hover:bg-[#e8f4ee] focus-within:ring-2 focus-within:ring-[#f08a24]"><ImagePlus className="size-4" aria-hidden="true" />Selecionar<input id="auction-cover" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setCover(e.target.files?.[0] ?? null)} disabled={readOnly} className="sr-only" /></label></div></Field>
      {notice ? <p role="status" className="rounded-xl border border-[#dfe8e2] bg-[#f3f9f5] px-4 py-3 text-sm text-[#075b3e]">{notice}</p> : null}<div className="flex justify-end"><button type="submit" disabled={readOnly || isPending} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#08734e] px-4 text-sm font-semibold text-white hover:bg-[#075b3e] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24] focus-visible:ring-offset-2 disabled:opacity-50"><Save className="size-4" aria-hidden="true" />{isPending ? "Salvando…" : "Salvar dados"}</button></div>
    </form>
  </section>;
}

function Field({ label, id, children }: { label: string; id: string; children: React.ReactNode }) { return <label htmlFor={id} className="block text-xs font-semibold text-slate-700">{label}{children}</label>; }
function TextAreaField({ label, id, value, onChange, disabled }: { label: string; id: string; value: string; onChange: (value: string) => void; disabled: boolean }) { return <Field label={label} id={id}><textarea id={id} value={value} onChange={(e) => onChange(e.target.value)} rows={5} disabled={disabled} className="admin-field mt-1.5 h-auto py-2" /></Field>; }
