"use client";

import { CheckCircle2, Circle, ExternalLink, FileBarChart, Gavel, ListOrdered, MonitorPlay, Settings2, ShieldCheck, XCircle } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useState, useTransition } from "react";
import { cancelAuctionAction, publishAuctionAction } from "@/hooks/actions/auctionActions";
import { formatAuctionDate, formatAuctionStatus, formatCents } from "@/lib/auctions/admin-utils";
import type { AuctionAdmin, AuctionAdminLot } from "@/types/auction-admin";
import type { EngineAuctionSnapshot } from "@/lib/auctions/engine-types";
import type { BroadcastClientInfo, BroadcastConfig, BroadcastState } from "@/lib/broadcast/broadcast-types";
import type { AuctionCapabilities } from "@/components/Management/capabilities";
import { AuctionForm } from "@/components/Management/AuctionForm";
import { AuctionLotsPanel } from "@/components/Management/AuctionLotsPanel";
import { AuctionOperationPanel } from "@/components/Management/AuctionOperationPanel";
import { AuctionParticipantsPanel } from "@/components/Management/AuctionParticipantsPanel";

type Tab = "resumo"|"dados"|"lotes"|"participantes"|"operacao"|"transmissao";
const tabs: Array<{value:Tab;label:string;icon:typeof Gavel}> = [{value:"resumo",label:"Resumo",icon:Gavel},{value:"dados",label:"Dados",icon:Settings2},{value:"lotes",label:"Lotes",icon:ListOrdered},{value:"participantes",label:"Participantes",icon:ShieldCheck},{value:"operacao",label:"Operação",icon:MonitorPlay},{value:"transmissao",label:"Broadcast / OBS",icon:MonitorPlay}];
function getTab(value:string|null):Tab{return tabs.some((tab)=>tab.value===value)?value as Tab:"resumo"}

export function AuctionWorkspace({auction, lots, capabilities, engineSnapshot, engineError, broadcastState, broadcastConfig, broadcastClients}:{auction:AuctionAdmin;lots:AuctionAdminLot[];capabilities:AuctionCapabilities;engineSnapshot:EngineAuctionSnapshot|null;engineError?:string;broadcastState:BroadcastState|null;broadcastConfig:BroadcastConfig|null;broadcastClients:BroadcastClientInfo[]}){const router=useRouter();const pathname=usePathname();const params=useSearchParams();const [tab,setTab]=useState<Tab>(getTab(params.get("aba")));function changeTab(next:Tab){setTab(next);router.replace(`${pathname}?aba=${next}`,{scroll:false})}const workspaceCaps={...capabilities,canEdit:capabilities.canEdit&&(auction.availableActions?.canEdit??true),canManageLots:capabilities.canManageLots&&(auction.availableActions?.canManageLots??true)};const ready=[Boolean(auction.title&&auction.category&&auction.startsAt),Boolean(auction.startsAt),Boolean(auction.coverImage||auction.coverImageUrl),lots.some((lot)=>["OPEN","SOLD","CLOSED"].includes(lot.status))];const completed=ready.filter(Boolean).length;
  return <div className="space-y-6"><header className="flex flex-col gap-4 border-b border-[#dfe8e2] pb-6"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admin/leiloes" className="text-sm font-semibold text-[#075b3e] underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24]">← Voltar aos leilões</Link><div className="flex flex-wrap gap-2"><Link href={`/admin/leiloes/${auction.id}/relatorio`} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-[#dfe8e2] px-3 text-sm font-semibold text-slate-700 hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24]"><FileBarChart className="size-4" aria-hidden="true"/>Relatório</Link><Link href={`/admin/leiloes/${auction.id}/broadcast`} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[#0d3427] px-3 text-sm font-semibold text-white hover:bg-[#075b3e] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24]"><MonitorPlay className="size-4" aria-hidden="true"/>Controlar transmissão</Link></div></div><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#e8f4ee] px-2.5 py-1 text-xs font-semibold text-[#075b3e]">{formatAuctionStatus(auction.status)}</span><span className="text-xs text-slate-500">{auction.mode} · {auction.slug}</span></div><h1 className="mt-2 text-3xl font-bold tracking-tight">{auction.title}</h1><p className="mt-2 text-sm text-slate-600">Início {formatAuctionDate(auction.startsAt)} · {auction.lotCount} lote(s) · incremento {formatCents(auction.incrementCents)}</p></div><AuctionStatusControls auction={auction} capabilities={capabilities}/></div></header>
    <nav className="overflow-x-auto rounded-2xl border border-[#dfe8e2] bg-white p-1 shadow-sm" aria-label="Seções do workspace"><div className="flex min-w-max gap-1">{tabs.map(({value,label,icon:Icon})=><button type="button" key={value} onClick={()=>changeTab(value)} aria-current={tab===value?"page":undefined} className={`inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24] sm:px-4 ${tab===value?"bg-[#0d3427] text-white":"text-slate-600 hover:bg-[#f3f9f5] hover:text-[#075b3e]"}`}><Icon className="size-4" aria-hidden="true"/>{label}</button>)}</div></nav>
    {tab==="resumo"?<div className="space-y-5"><section className="rounded-2xl border border-[#dfe8e2] bg-white p-5 shadow-sm" aria-labelledby="readiness-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="readiness-title" className="font-semibold">Prontidão para publicar</h2><p className="mt-1 text-sm text-slate-600">{completed} de {ready.length} itens concluídos</p></div><span className="text-3xl font-bold text-[#08734e]">{Math.round((completed/ready.length)*100)}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#e8f4ee]"><div className="h-full rounded-full bg-[#08734e] transition-[width] duration-300" style={{width:`${(completed/ready.length)*100}%`}}/></div><ul className="mt-4 grid gap-2 sm:grid-cols-2">{[["Dados básicos",ready[0],"dados"],["Agenda configurada",ready[1],"dados"],["Capa adicionada",ready[2],"dados"],["Lote visível",ready[3],"lotes"]].map(([label,done,target])=><li key={String(label)} className="flex items-center justify-between gap-3 rounded-xl bg-[#fbfdfb] px-3 py-3 text-sm"><span className="flex items-center gap-2">{done?<CheckCircle2 className="size-4 text-[#08734e]" aria-hidden="true"/>:<Circle className="size-4 text-slate-400" aria-hidden="true"/>}{label}</span>{!done?<button type="button" onClick={()=>changeTab(target as Tab)} className="text-xs font-semibold text-[#075b3e] underline-offset-4 hover:underline">Corrigir</button>:null}</li>)}</ul></section><div className="grid overflow-hidden rounded-2xl border border-[#dfe8e2] bg-white shadow-sm sm:grid-cols-2 xl:grid-cols-4"><Metric label="Formato" value={auction.mode==="LIVE"?"Leilão ao vivo":auction.mode==="SHOPPING"?"Shopping":"Pré-lance"}/><Metric label="Início" value={formatAuctionDate(auction.startsAt)}/><Metric label="Encerramento" value={formatAuctionDate(auction.endsAt)}/><Metric label="Lotes" value={`${auction.lotCount} · ${formatCents(auction.incrementCents)}`}/></div>{auction.availableActions?.reasons.publish?<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><p className="font-semibold">Publicação pendente</p><p className="mt-1">{auction.availableActions.reasons.publish.message}</p></div>:null}</div>:null}
    {tab==="dados"?<AuctionForm initialData={auction} capabilities={workspaceCaps}/>:null}{tab==="lotes"?<AuctionLotsPanel auctionId={auction.id} initialLots={lots} capabilities={capabilities} engineLots={engineSnapshot?.lots}/>:null}{tab==="participantes"?<AuctionParticipantsPanel auctionId={auction.id} capabilities={capabilities}/>:null}{tab==="operacao"?<AuctionOperationPanel auctionId={auction.id} initialSnapshot={engineSnapshot} capabilities={capabilities}/>:null}{tab==="transmissao"?<BroadcastSummary auctionId={auction.id} state={broadcastState} config={broadcastConfig} clients={broadcastClients} error={engineError}/>:null}
  </div>}

function Metric({label,value}:{label:string;value:string}){return <div className="border-b border-[#e9efeb] p-4 last:border-b-0 sm:border-r sm:last:border-r-0 xl:border-b-0"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function AuctionStatusControls({auction,capabilities}:{auction:AuctionAdmin;capabilities:AuctionCapabilities}){const [notice,setNotice]=useState<string|null>(null);const [pending,startTransition]=useTransition();function publish(){startTransition(async()=>{const result=await publishAuctionAction(auction.id);setNotice(result.success?"Leilão publicado.":result.error||"Não foi possível publicar.");if(result.success)window.location.reload()})}function cancel(){if(!window.confirm("Cancelar este leilão?"))return;startTransition(async()=>{const result=await cancelAuctionAction(auction.id);setNotice(result.success?"Leilão cancelado.":result.error||"Não foi possível cancelar.");if(result.success)window.location.reload()})}const canPublish=capabilities.canManageStatus&&auction.availableActions?.canPublish!==false&&auction.status!=="OPEN"&&auction.status!=="CLOSED"&&auction.status!=="CANCELLED";return <div className="flex flex-wrap items-center gap-2">{notice?<span role="status" className="text-xs font-semibold text-slate-600">{notice}</span>:null}{canPublish?<button type="button" onClick={publish} disabled={pending} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[#08734e] px-3 text-sm font-semibold text-white hover:bg-[#075b3e] disabled:opacity-50"><CheckCircle2 className="size-4" aria-hidden="true"/>Publicar</button>:null}{capabilities.canManageStatus&&auction.status!=="CANCELLED"&&auction.status!=="CLOSED"?<button type="button" onClick={cancel} disabled={pending} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-red-200 px-3 text-sm font-semibold text-red-700 hover:bg-red-50 disabled:opacity-50"><XCircle className="size-4" aria-hidden="true"/>Cancelar</button>:null}</div>}
function BroadcastSummary({auctionId,state,config,clients,error}:{auctionId:string;state:BroadcastState|null;config:BroadcastConfig|null;clients:BroadcastClientInfo[];error?:string}){return <section className="space-y-5" aria-labelledby="broadcast-summary-title"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[#08734e]"><MonitorPlay className="size-5" aria-hidden="true"/><p className="text-xs font-bold uppercase tracking-[0.16em]">Transmissão</p></div><h2 id="broadcast-summary-title" className="mt-2 text-xl font-bold">Broadcast / OBS</h2><p className="mt-1 text-sm text-slate-600">O overlay é somente leitura; comandos de leilão continuam no Auction Engine.</p></div><Link href={`/admin/leiloes/${auctionId}/broadcast`} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[#0d3427] px-3 text-sm font-semibold text-white hover:bg-[#075b3e] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08a24]"><ExternalLink className="size-4" aria-hidden="true"/>Abrir control room</Link></div>{error?<p className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{error}</p>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Status" value={state?.status??"Sem snapshot"}/><Metric label="Lote atual" value={state?.currentLot?`Lote ${state.currentLot.number} · ${state.currentLot.title}`:"Nenhum"}/><Metric label="Versão" value={state?String(state.version):"—"}/><Metric label="Clientes / delay" value={`${clients.length} · ${config?.overlayDelayMs??0} ms`}/></div>}</section>}
