import type { Metadata } from "next";
import Link from "next/link";
import { ReportPrintButton } from "@/components/Management/ReportPrintButton";
import { getAdminAuctionAction, getAdminAuctionReportAction } from "@/hooks/actions/auctionActions";
import { formatAuctionDate, formatCents, formatLotStatus } from "@/lib/auctions/admin-utils";
import { permissionsToAuctionCapabilities } from "@/components/Management/capabilities";
import { getAuctionManagementAccess } from "@/lib/permissions/server/auction-access";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Relatório do leilão" };
export default async function AuctionReportPage({ params }: { params: Promise<{ id:string }> }) { const {id}=await params; const { session, permissions } = await getAuctionManagementAccess(); const capabilities = permissionsToAuctionCapabilities(permissions, session.user.accountType); if (!capabilities.canViewReports) return <section className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-800"><h1 className="font-semibold">Acesso negado</h1><p className="mt-1">Seu perfil não possui a permissão para consultar relatórios.</p></section>; const [auction,report]=await Promise.all([getAdminAuctionAction(id),getAdminAuctionReportAction(id)]); if(!report.success||!report.data)return <section className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-800"><h1 className="font-semibold">Relatório indisponível</h1><p className="mt-1">{report.error||"Não foi possível carregar o relatório."}</p></section>; const data=report.data; return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href={`/admin/leiloes/${id}`} className="text-sm font-semibold text-[#075b3e] underline-offset-4 hover:underline">← Voltar ao workspace</Link><h1 className="mt-3 text-3xl font-bold">Relatório do leilão</h1><p className="mt-2 text-sm text-slate-600">{auction.data?.title??data.auction.title} · {formatAuctionDate(data.auction.startsAt)}</p></div><ReportPrintButton /></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Lotes" value={String(data.totals?.lots??data.lots.length)}/><Metric label="Vendidos" value={String(data.totals?.sold??data.lots.filter((lot)=>lot.status==="SOLD").length)}/><Metric label="Total" value={formatCents(data.totals?.grossCents)}/></div><div className="overflow-hidden rounded-2xl border border-[#dfe8e2] bg-white shadow-sm"><div className="hidden grid-cols-[6rem_1fr_9rem_12rem_7rem] gap-3 border-b border-[#e9efeb] bg-[#fbfdfb] px-4 py-3 text-xs font-bold uppercase tracking-[0.08em] text-slate-500 md:grid"><span>Lote</span><span>Título</span><span>Status</span><span>Vencedor</span><span>Valor</span></div><div className="divide-y divide-[#e9efeb]">{data.lots.map((lot)=><div key={lot.id} className="grid gap-2 px-4 py-4 text-sm md:grid-cols-[6rem_1fr_9rem_12rem_7rem] md:items-center md:gap-3"><span className="font-semibold">Lote {String(lot.number).padStart(2,"0")}</span><span>{lot.title}</span><span className="w-fit rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{formatLotStatus(lot.status as Parameters<typeof formatLotStatus>[0])||lot.status}</span><span className="text-slate-600">{lot.currentBidderName||"—"}</span><span className="font-semibold tabular-nums">{formatCents(lot.currentBidCents)}</span></div>)}</div></div></section> }
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#dfe8e2] bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-[#08734e]">{value}</p></div>}
